/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.CardLayout;

/**
 *
 * @author Katarzyna
 */
public class EditWindow extends javax.swing.JFrame {

    /**
     * Creates new form EditWindow
     */
    public EditWindow() {
        initComponents();
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel,"cleanPanel");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        teacherPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastnameFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addTeacherButton = new javax.swing.JButton();
        mathBox = new javax.swing.JCheckBox();
        polishBox = new javax.swing.JCheckBox();
        englishBox = new javax.swing.JCheckBox();
        germanBox = new javax.swing.JCheckBox();
        biologyBox = new javax.swing.JCheckBox();
        chemistryBox = new javax.swing.JCheckBox();
        physicsBox = new javax.swing.JCheckBox();
        russianBox = new javax.swing.JCheckBox();
        religionBox = new javax.swing.JCheckBox();
        ethicsBox = new javax.swing.JCheckBox();
        geographyBox = new javax.swing.JCheckBox();
        edbBox = new javax.swing.JCheckBox();
        peBox = new javax.swing.JCheckBox();
        historyBox = new javax.swing.JCheckBox();
        itBox = new javax.swing.JCheckBox();
        wosBox = new javax.swing.JCheckBox();
        wdzBoz = new javax.swing.JCheckBox();
        artBox = new javax.swing.JCheckBox();
        ppBox = new javax.swing.JCheckBox();
        italianBox = new javax.swing.JCheckBox();
        frenchBox = new javax.swing.JCheckBox();
        spanishBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        groupPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        classField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        addClassButton = new javax.swing.JButton();
        cleanPanel = new javax.swing.JPanel();
        teacherPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lessonPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        groupList = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        classList = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        teacherList = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        mondayRadioBtn = new javax.swing.JRadioButton();
        tuesdayRadioBtn = new javax.swing.JRadioButton();
        wednesdayRadioBtn = new javax.swing.JRadioButton();
        thursdayRadioBtn = new javax.swing.JRadioButton();
        fridayRadioBtn = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        hourList = new javax.swing.JComboBox<>();
        previewPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addLessonBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        newMenu = new javax.swing.JMenu();
        groupItem1 = new javax.swing.JMenuItem();
        teachersItem1 = new javax.swing.JMenuItem();
        classItem1 = new javax.swing.JMenuItem();
        lessonItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        groupItem2 = new javax.swing.JMenuItem();
        teachersItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());

        teacherPanel.setToolTipText("");
        teacherPanel.setOpaque(false);

        jLabel1.setLabelFor(nameField);
        jLabel1.setText("Wprowadź dane nowego nauczyciela");

        jLabel2.setText("Imię");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        jLabel3.setLabelFor(lastnameFiled);
        jLabel3.setText("Nazwisko");

        jLabel4.setText("Przedmioty");

        addTeacherButton.setText("Dodaj");
        addTeacherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeacherButtonActionPerformed(evt);
            }
        });

        mathBox.setText("Matematyka");
        mathBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathBoxActionPerformed(evt);
            }
        });

        polishBox.setText("Język polski");

        englishBox.setText("Język anglieski");

        germanBox.setText("Język niemiecki");

        biologyBox.setText("Biologia");

        chemistryBox.setText("Chemia");

        physicsBox.setText("Fizyka");

        russianBox.setText("Język rosyjski");

        religionBox.setText("Religia");

        ethicsBox.setText("Etyka");

        geographyBox.setText("Geografia");
        geographyBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geographyBoxActionPerformed(evt);
            }
        });

        edbBox.setText("Edukacja dla bezpieczeństwa");

        peBox.setText("Wychowanie fizyczne");

        historyBox.setText("Historia");

        itBox.setText("Informatyka");

        wosBox.setText("Wiedza o społeczeństwie");

        wdzBoz.setText("Wychowanie do życia w rodzinie");

        artBox.setText("Kultura");

        ppBox.setText("Podstawy przedsiębiorczości");

        italianBox.setText("Język włoski");

        frenchBox.setText("Język francuski");

        spanishBox.setText("Język hiszpański");

        jLabel8.setText("ID");

        javax.swing.GroupLayout teacherPanelLayout = new javax.swing.GroupLayout(teacherPanel);
        teacherPanel.setLayout(teacherPanelLayout);
        teacherPanelLayout.setHorizontalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mathBox)
                            .addComponent(biologyBox)
                            .addComponent(chemistryBox)
                            .addComponent(physicsBox)
                            .addComponent(geographyBox)
                            .addComponent(itBox)
                            .addComponent(historyBox))
                        .addGap(45, 45, 45)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(polishBox)
                            .addComponent(englishBox)
                            .addComponent(germanBox)
                            .addComponent(russianBox)
                            .addComponent(italianBox)
                            .addComponent(frenchBox)
                            .addComponent(spanishBox))
                        .addGap(56, 56, 56)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wosBox)
                            .addComponent(religionBox)
                            .addComponent(ethicsBox)
                            .addComponent(edbBox)
                            .addComponent(peBox)
                            .addComponent(wdzBoz)
                            .addComponent(artBox)
                            .addComponent(ppBox)))
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(teacherPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lastnameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(teacherPanelLayout.createSequentialGroup()
                                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39)
                        .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        teacherPanelLayout.setVerticalGroup(
            teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addComponent(addTeacherButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(teacherPanelLayout.createSequentialGroup()
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(1, 1, 1)))
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mathBox)
                    .addComponent(polishBox)
                    .addComponent(religionBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(englishBox)
                    .addComponent(biologyBox)
                    .addComponent(ethicsBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(germanBox)
                    .addComponent(chemistryBox)
                    .addComponent(edbBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(physicsBox)
                    .addComponent(russianBox)
                    .addComponent(peBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(geographyBox)
                    .addComponent(wdzBoz)
                    .addComponent(italianBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itBox)
                    .addComponent(wosBox)
                    .addComponent(frenchBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(teacherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artBox)
                    .addComponent(historyBox)
                    .addComponent(spanishBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ppBox)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        mainPanel.add(teacherPanel, "teacherPanel");

        groupPanel.setPreferredSize(new java.awt.Dimension(596, 328));

        jLabel5.setText("Dodaj nową klasę");

        jLabel6.setText("Klasa");

        jLabel7.setText("Wychowawca");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        addClassButton.setText("Dodaj");
        addClassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout groupPanelLayout = new javax.swing.GroupLayout(groupPanel);
        groupPanel.setLayout(groupPanelLayout);
        groupPanelLayout.setHorizontalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(groupPanelLayout.createSequentialGroup()
                        .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(groupPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(classField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, groupPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        groupPanelLayout.setVerticalGroup(
            groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(groupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addClassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(groupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(329, Short.MAX_VALUE))
        );

        mainPanel.add(groupPanel, "groupPanel");

        javax.swing.GroupLayout cleanPanelLayout = new javax.swing.GroupLayout(cleanPanel);
        cleanPanel.setLayout(cleanPanelLayout);
        cleanPanelLayout.setHorizontalGroup(
            cleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        cleanPanelLayout.setVerticalGroup(
            cleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 434, Short.MAX_VALUE)
        );

        mainPanel.add(cleanPanel, "cleanPanel");

        jLabel9.setText("Wybierz nauczyciela którego dane chcesz edytować");

        javax.swing.GroupLayout teacherPanel2Layout = new javax.swing.GroupLayout(teacherPanel2);
        teacherPanel2.setLayout(teacherPanel2Layout);
        teacherPanel2Layout.setHorizontalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        teacherPanel2Layout.setVerticalGroup(
            teacherPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacherPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(409, Short.MAX_VALUE))
        );

        mainPanel.add(teacherPanel2, "teacherPanel2");

        jLabel10.setText("Dodaj nową lekcję");

        jLabel11.setText("Klasa");

        groupList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Sala");

        classList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel13.setText("Nauczyciel");

        teacherList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Dzień");

        mondayRadioBtn.setText("Poniedziałek");
        mondayRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mondayRadioBtnActionPerformed(evt);
            }
        });

        tuesdayRadioBtn.setText("Wtorek");

        wednesdayRadioBtn.setText("Środa");
        wednesdayRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wednesdayRadioBtnActionPerformed(evt);
            }
        });

        thursdayRadioBtn.setText("Czwartek");

        fridayRadioBtn.setText("Piątek");

        jLabel15.setText("Godzina");

        hourList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("tutaj będzie się znajdował podgląd planu uaktualniany po \ndodaniu nowej lekcji");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout previewPanelLayout = new javax.swing.GroupLayout(previewPanel);
        previewPanel.setLayout(previewPanelLayout);
        previewPanelLayout.setHorizontalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        previewPanelLayout.setVerticalGroup(
            previewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previewPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        addLessonBtn.setText("Dodaj");
        addLessonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lessonPanelLayout = new javax.swing.GroupLayout(lessonPanel);
        lessonPanel.setLayout(lessonPanelLayout);
        lessonPanelLayout.setHorizontalGroup(
            lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(lessonPanelLayout.createSequentialGroup()
                            .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)
                            .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tuesdayRadioBtn)
                                .addComponent(mondayRadioBtn)
                                .addComponent(wednesdayRadioBtn)
                                .addComponent(thursdayRadioBtn)
                                .addComponent(fridayRadioBtn)
                                .addComponent(hourList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lessonPanelLayout.createSequentialGroup()
                            .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(groupList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(classList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teacherList, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(addLessonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(previewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lessonPanelLayout.setVerticalGroup(
            lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lessonPanelLayout.createSequentialGroup()
                .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lessonPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(groupList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(classList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teacherList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(mondayRadioBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tuesdayRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wednesdayRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thursdayRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fridayRadioBtn)
                        .addGap(2, 2, 2)
                        .addGroup(lessonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(hourList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(addLessonBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(previewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 97, Short.MAX_VALUE))
        );

        mainPanel.add(lessonPanel, "lessonPanel");

        newMenu.setText("Nowy");

        groupItem1.setText("Grupy");
        groupItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupItem1ActionPerformed(evt);
            }
        });
        newMenu.add(groupItem1);

        teachersItem1.setText("Nauczyciele");
        teachersItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersItem1ActionPerformed(evt);
            }
        });
        newMenu.add(teachersItem1);

        classItem1.setText("Sale");
        newMenu.add(classItem1);

        lessonItem.setText("Lekcje");
        lessonItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessonItemActionPerformed(evt);
            }
        });
        newMenu.add(lessonItem);

        jMenuBar1.add(newMenu);

        editMenu.setText("Edytuj");

        groupItem2.setText("Grupy");
        groupItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupItem2ActionPerformed(evt);
            }
        });
        editMenu.add(groupItem2);

        teachersItem2.setText("Nauczyciele");
        editMenu.add(teachersItem2);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupItem1ActionPerformed
        if(evt.getSource() == groupItem1) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel,"groupPanel");
        }
    }//GEN-LAST:event_groupItem1ActionPerformed

    private void teachersItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersItem1ActionPerformed
        if(evt.getSource()==teachersItem1) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel,"teacherPanel");
            
        }
    }//GEN-LAST:event_teachersItem1ActionPerformed

    private void addClassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addClassButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void geographyBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geographyBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_geographyBoxActionPerformed

    private void mathBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathBoxActionPerformed

    private void addTeacherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeacherButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeacherButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void groupItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groupItem2ActionPerformed

    private void mondayRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mondayRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mondayRadioBtnActionPerformed

    private void wednesdayRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wednesdayRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wednesdayRadioBtnActionPerformed

    private void addLessonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLessonBtnActionPerformed

    private void lessonItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessonItemActionPerformed
        if(evt.getSource()==lessonItem) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel,"lessonPanel");
            
        }
    }//GEN-LAST:event_lessonItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditWindow().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClassButton;
    private javax.swing.JButton addLessonBtn;
    private javax.swing.JButton addTeacherButton;
    private javax.swing.JCheckBox artBox;
    private javax.swing.JCheckBox biologyBox;
    private javax.swing.JCheckBox chemistryBox;
    private javax.swing.JTextField classField;
    private javax.swing.JMenuItem classItem1;
    private javax.swing.JComboBox<String> classList;
    private javax.swing.JPanel cleanPanel;
    private javax.swing.JCheckBox edbBox;
    private javax.swing.JMenu editMenu;
    private javax.swing.JCheckBox englishBox;
    private javax.swing.JCheckBox ethicsBox;
    private javax.swing.JCheckBox frenchBox;
    private javax.swing.JRadioButton fridayRadioBtn;
    private javax.swing.JCheckBox geographyBox;
    private javax.swing.JCheckBox germanBox;
    private javax.swing.JMenuItem groupItem1;
    private javax.swing.JMenuItem groupItem2;
    private javax.swing.JComboBox<String> groupList;
    private javax.swing.JPanel groupPanel;
    private javax.swing.JCheckBox historyBox;
    private javax.swing.JComboBox<String> hourList;
    private javax.swing.JTextField idField;
    private javax.swing.JCheckBox itBox;
    private javax.swing.JCheckBox italianBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField lastnameFiled;
    private javax.swing.JMenuItem lessonItem;
    private javax.swing.JPanel lessonPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JCheckBox mathBox;
    private javax.swing.JRadioButton mondayRadioBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JMenu newMenu;
    private javax.swing.JCheckBox peBox;
    private javax.swing.JCheckBox physicsBox;
    private javax.swing.JCheckBox polishBox;
    private javax.swing.JCheckBox ppBox;
    private javax.swing.JPanel previewPanel;
    private javax.swing.JCheckBox religionBox;
    private javax.swing.JCheckBox russianBox;
    private javax.swing.JCheckBox spanishBox;
    private javax.swing.JComboBox<String> teacherList;
    private javax.swing.JPanel teacherPanel;
    private javax.swing.JPanel teacherPanel2;
    private javax.swing.JMenuItem teachersItem1;
    private javax.swing.JMenuItem teachersItem2;
    private javax.swing.JRadioButton thursdayRadioBtn;
    private javax.swing.JRadioButton tuesdayRadioBtn;
    private javax.swing.JCheckBox wdzBoz;
    private javax.swing.JRadioButton wednesdayRadioBtn;
    private javax.swing.JCheckBox wosBox;
    // End of variables declaration//GEN-END:variables
}
